name: little_guardian
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# 주요 패키지 종속성 (dependencies)
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_webrtc: ^0.11.7  # WebRTC 지원
  lottie: ^3.1.2  # Lottie 애니메이션 지원
  flutter_native_splash: ^2.4.1

  # 파이어 베이스 관련
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2

# 개발 관련 패키지 종속성 (dev_dependencies)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#9dc0e3"
  image: assets/splashIcon.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

# Flutter 앱 설정
flutter:
  uses-material-design: true  # Material Icons 사용

  # 애셋 설정 (assets)
  assets:
    - assets/  # 기본 애셋 디렉토리
    - assets/lottie/  # Lottie 애니메이션 파일 디렉토리
    - assets/image/

  # 폰트 설정 (fonts)
  fonts:
    - family: NanumSquareNeo  # 폰트 패밀리: NanumSquareNeo
      fonts:
        - asset: assets/fonts/NanumSquareNeo-aLt.ttf
          weight: 300  # Light
        - asset: assets/fonts/NanumSquareNeo-bRg.ttf
          weight: 700  # Bold
        - asset: assets/fonts/NanumSquareNeo-dEb.ttf
          weight: 800  # ExtraBold
        - asset: assets/fonts/NanumSquareNeo-eHv.ttf
          weight: 400  # Regular
        - asset: assets/fonts/NanumSquareNeo-cBd.ttf
          weight: 900  # Heavy
    - family: jalnan  # 폰트 패밀리: jalnan
      fonts:
        - asset: assets/fonts/Jalnan2TTF.ttf
